# -*- coding: utf-8 -*-
"""url_phishing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jmRyPWrEHA-GJqLZ526rBsFMRPgjKqOC
"""



# user_url = input('what url would you like to check?')

def analyze_url(user_url):
    import pickle

    loaded_model = pickle.load(open('phishing.pkl', 'rb'))
    new_list = [user_url]

    result = loaded_model.predict(new_list)
    return result